language: python

python:
  - "2.7"

env:
  - VERSION="8.0" ODOO_REPO="odoo/odoo"
  - VERSION="8.0" ODOO_REPO="OCA/OCB"

virtualenv:
  system_site_packages: true

install:
  - pip install unidecode
  - git clone https://github.com/OCA/partner-contact ${HOME}/partner-contact -b ${VERSION}
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - bzr branch lp:acysos/openerp-addons-8.0 ${HOME}/acysos-addons
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly ${VERSION}

script:
  - travis_run_flake8
  - travis_run_tests ${VERSION} ${HOME}/partner-contact ${HOME}/maintainer-quality-tools ${HOME}/acysos-addons

after_success:
  coveralls
