language: python

python:
  - "2.7"

sudo: false
cache: pip

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-xlrd

env:
  global:
  - VERSION="8.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"
  - TRANSIFEX_USER='transbot@odoo-community.org'
  - secure: "XLhGdCIh86zcqww9qBpnk8Xqsf1Pcgw9SKr7X0KYBHJofHj4Z6Kq/oVFjpZ1LSjadsaABKbwY7h4hvKEpxZwptCv+fNTOKYy7hXFLGYnDeNeWu4zA4LI7TA5uPvyZjZ+g2xc+9dzR/VbfRHNqjvmgiEidxxqLeOnNFZ5CHdOdCw="
  matrix:
  - LINT_CHECK="1"
  - TRANSIFEX="1"
  - TESTS="1" ODOO_REPO="odoo/odoo" OPTIONS="--test-commit" EXCLUDE="l10n_es_toponyms,l10n_es_partner"
  - TESTS="1" ODOO_REPO="OCA/OCB" OPTIONS="--test-commit" EXCLUDE="l10n_es_toponyms,l10n_es_partner"

virtualenv:
  system_site_packages: true

install:
  - pip install unidecode
  - pip install unicodecsv
  - pip install requests
  - git clone https://github.com/vauxoo-dev/maintainer-quality-tools.git -b master-oca-add-coloured-moy ${HOME}/maintainer-quality-tools
  - (cd ${HOME}/maintainer-quality-tools;git pull origin master-oca-profiling-moy)
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_wait travis_run_tests

after_success:
  - travis_after_tests_success
