language: python
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

python:
  - "3.6"

addons:
  apt:
# only add the two lines below if you need wkhtmltopdf for your tests
#    sources:
#      - pov-wkhtmltopdf
#    Search your sources alias here:
#      https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml
#     Search your packages here:
#       https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
#      - wkhtmltopdf  # only add if needed and check the before_install section below

# set up an X server to run wkhtmltopdf.
#before_install:
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"

# Sometimes complicated website repos need Compass & SaSS:
#before_install:
#  - rvm install ruby --latest
#  - gem install bootstrap-sass
#  - gem install compass --pre

env:
  global:
  - VERSION="10.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"
  # - WKHTMLTOPDF_VERSION="0.12.4"
  # Set the above to install a `wkhtmltopdf` version that is not the one provided
  # by the `pov-wkhtmltopdf` repo.
  - PHANTOMJS_VERSION="latest"
  # The above line controls the PhantomJS version that is used for JS testing.
  #   It is not necessary to include this value unless you are altering the default.
  #   Use `OS` to skip the PhantomJS upgrade & use the system version instead.
  - WEBSITE_REPO="1"
  # Use the above line to install dependencies that are required for website repos:
  # * SASS & Bootstrap-SASS
  # * Compass
  - TRANSIFEX_USER='transbot@odoo-community.org'
  # This line contains the encrypted transifex password
  # To encrypt transifex password, install travis ruby utils with:
  #   $ gem install travis --user-install
  # and use:
  #   $ travis encrypt TRANSIFEX_PASSWORD=your-password -r owner/project
  # Secure list for current OCA projects is in https://github.com/OCA/maintainer-quality-tools/issues/194
  - secure: cDar6TO5rvacLDDg1VWPTDqVET/lmeFlipI+IfivoBVXYJFWewOfTT8o40Qggr5lytow/fLvnqaksvnHbfLDYV1UgKqI+wzk/WaLEvRyNrZb+L+Ovm/kXT/af8T7Aa0bXs1tCJvuZpvTL8KuPKdjMI8pDaD1Oda2/1OI8uKvpXY=
  # Use the following lines if you need to manually change the transifex project slug or/and the transifex organization.
  # The default project slug is owner-repo_name-version (with dash in the version string).
  # The default organization is the owner of the repo.
  # The default fill up resources (TM) is True.
  # The default team is 23907. https://www.transifex.com/organization/oca/team/23907/
  # - TRANSIFEX_PROJECT_SLUG=
  # - TRANSIFEX_ORGANIZATION=
  # - TRANSIFEX_FILL_UP_RESOURCES=
  # - TRANSIFEX_TEAM=

  matrix:
  - LINT_CHECK="1"
  - TRANSIFEX="1"
  - TESTS="1" ODOO_REPO="odoo/odoo"
  - TESTS="1" ODOO_REPO="OCA/OCB"
# either use the two lines above or the two below. Don't change the default if
# it's not necessary (it is only necessary if modules in your repository can't
# be installed in the same database. And you get a huge speed penalty in your
# tests)
#  - TESTS="1.0" ODOO_REPO="odoo/odoo" UNIT_TEST="1"
#  - TESTS="1.0" ODOO_REPO="OCA/OCB" UNIT_TEST="1"

virtualenv:
  system_site_packages: true

# Enable this if your repository needs sass command (needed for website related repos)
#before_install:
#  - rvm install ruby --latest
#  - gem install bootstrap-sass
#  - gem install compass --pre

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
# Use the sentence below to install a specific wkhtmltopdf version
# - export WKHTMLTOPDF_VERSION=0.12.4

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
